# Whisper outputs the recognized language as 2-letter code (ISO 639-1)
# (see https://github.com/huggingface/transformers/blob/main/src/transformers/models/whisper/tokenization_whisper.py)
# but IMS Toucan requires them as 3-letter code (ISO 639-3)
# (see https://github.com/DigitalPhonetics/IMS-Toucan/blob/MassiveScaleToucan/Preprocessing/multilinguality/iso_lookup.json)

from transformers.models.whisper.tokenization_whisper import TO_LANGUAGE_CODE

LANG_CODES = {
    'en': 'eng',
    'zh': 'cmn',
    'de': 'deu',
    'es': 'spa',
    'ru': 'rus',
    'ko': 'kor',
    'fr': 'fra',
    'ja': 'jpn',
    'pt': 'por',
    'tr': 'tur',
    'pl': 'pol',
    'ca': 'cat',
    'nl': 'nld',
    'ar': 'arb',
    'sv': 'swe',
    'it': 'ita',
    'id': 'ind',
    'hi': 'hin',
    'fi': 'fin',
    'vi': 'vie',
    'he': 'heb',
    'uk': 'ukr',
    'el': 'ell',
    'ms': 'zlm',
    'cs': 'ces',
    'ro': 'ron',
    'da': 'dan',
    'hu': 'hun',
    'ta': 'tam',
    'no': 'nor',
    'th': 'tha',
    'ur': 'urd',
    'hr': 'hrv',
    'bg': 'bul',
    'lt': 'lit',
    'la': 'lat',
    'mi': 'mri',
    'ml': 'mal',
    'cy': 'cym',
    'sk': 'slk',
    'te': 'tel',
    'fa': 'pes',
    'lv': 'lav',
    'bn': 'ben',
    'sr': 'srp',
    'az': 'azj',
    'sl': 'slv',
    'kn': 'kan',
    'et': 'ekk',
    'mk': 'mkd',
    'br': 'bre',
    'eu': 'eus',
    'is': 'isl',
    'hy': 'hye',
    'ne': 'nep',
    'mn': 'khk',
    'bs': 'bos',
    'kk': 'kaz',
    'sq': 'aln',
    'sw': 'swh',
    'gl': 'glg',
    'mr': 'mar',
    'pa': 'pan',
    'si': 'sin',
    'km': 'khm',
    'sn': 'sna',
    'yo': 'yor',
    'so': 'som',
    'af': 'afr',
    'oc': 'oci',
    'ka': 'kat',
    'be': 'bel',
    'tg': 'tgk',
    'sd': 'snd',
    'gu': 'guj',
    'am': 'amh',
    'yi': 'ydd',
    'lo': 'lao',
    'uz': 'uzn',
    'fo': 'fao',
    'ht': 'hat',
    'ps': 'pst',
    'tk': 'tuk',
    'nn': 'nor',
    'mt': 'mlt',
    'sa': 'san',
    'lb': 'ltz',
    'my': 'mya',
    'bo': 'bod',
    'tl': 'tgl',
    'mg': 'plt',
    'as': 'asm',
    'tt': 'tat',
    'haw': 'haw',
    'ln': 'lin',
    'ha': 'hau',
    'ba': 'bak',
    'jw': 'jav',
    'su': 'sun',
    'yue': 'yue'
}

LANG_NAMES2CODES = {lang_name: LANG_CODES[code] for lang_name, code in TO_LANGUAGE_CODE.items()}

LANGS_LONG2SHORT = {long: short for short, long in LANG_CODES.items()}
LANGS_SHORT2LONG = LANG_CODES